### PR TITLE
Use params to construct SQL strings

### PR DESCRIPTION
**Pull request by ic4f**
This should properly escape the placeholder values. Given that the *encrypted* `galaxy_session_id` is the only value originating from a cookie, there are no immediate security concerns. However, with a sufficient amount of copy and paste, it is not impossible for the current handling of SQL strings to eventually cause issues.

Ping @hexylena 
Also, @natefoo: is what we discussed.

(I'm working on a fork for main, but wanted to share this potential concern ASAP, just in case).

NOTES: 
- these parentheses `(%s || ' hours')` are needed due to the `||` operator precedence.
- `cursor.execute(sql, params)` where `params` is `None` is OK.

Tested this manually; no automated tests yet.

### CODE REVIEW

**Comment by hexylena** [comment]
This looks good, I should've caught that.

**Comment by ic4f** [comment]
Thank you for such a fast review+merge!

**Comment by hexylena** [comment]
It's pretty important :) 

I look forward to main's contributions! (We can add you or whoever is responsible to this repo if you like?)

**Comment by ic4f** [comment]
Yes, please, that would be great. (and yes, that would be me)

**Pull request merged**
