### PR TITLE
Improve gdpr/email validation handling

### PR DESCRIPTION
**Pull request by ic4f**
This builds upon 3 commits submitted in #12 and #13 (sorry for making this convoluted; trying to keep PRs atomic; will rebase after those two are merged).

This solves #8. 

Relevant details:

**Why custom email validator:**
This is needed for validating email values that may have been redacted (so we have a redaction code instead of a valid email): it extends the built-in `EmailValidator` and circumvents the validation when the email value has a recognized prefix.

The reason why we use a prefix and not a complete value is because redaction codes may differ across installations, so the validator will validate "[the-one-prefix]-gdpr" as well as "[the-one-prefix]-us-too".

**Why use `CharField` for email:**
We need to replace the default `EmailValidator` with the custom `EmailFormatValidator` on that field. I think this is a reasonable approach because an `EmailField` is just a `CharField` with an email validator - so we're not changing anything beyond replacing the default validator (which we still utilize after checking for the one case we exclude from email validation). One alternative is to override the validation on the admin, but, I think, there's no sane way to do that (the model has an email field, and it will validate it in the end as such, unless we *remove* the `EmailValidator` from its `default_validators`, etc.)

We run standard email validation on the user-facing form to prevent them from using a valid redaction code as their email. Because they can do that.

### CODE REVIEW

**Comment by hexylena** [comment]
I know you've put a lot of work into this so I'm sorry in advance for this comment, but I'd like to propose an alternative solution and see what you think.

1. Just use an email field, make the redaction code their name or their email before the @.
2. Store `redacted@example.com` if it's been wiped out, not something that's a sum type of email + some specified text.

rationale:

1. I *super* do not care about the redacted reason/text. If GDPR is too european for american tastes we can definitely go for the more american/cia-friendly "redacted" :P
2. Why make the text a knob to configure, no one is going to touch it, it's enough that we have a date based redaction method, and the email goes away.
3. keeping it with email field and getting the nice things possible from using that field is probably safer/easier in the long run? also less testing/validataion required.

Some comments on the content:

- migration 10 + 11 touch the same field, so there probably doesn't need to be two. Could you remove both and then regen the migrations, it'll output just one then.

> trying to keep PRs atomic

feel free to keep commits atomic, and put multiple in one PR, probably easier than tracking ordering of multiple PRs?

**Comment by ic4f** [comment]
> I know you've put a lot of work into this so 

No worries! Sometimes building a prototype is easier than describing it; so changing stuff or taking a different approach, etc. - all normal flow.

Since you're not keen on recording "gdpr" as the reason - great, let's keep it simple. I wasn't sure about the whole prefix idea, I did it in case recording the reason was essential. So yes, the less knobs - the better!

I'll rewrite this, combining migrations 10 and 11. 

> feel free to keep commits atomic, and put multiple in one PR, probably easier than tracking ordering of multiple PRs?

Thanks, was never sure how to handle that, will do.

**Comment by hexylena** [comment]
> No worries! Sometimes building a prototype is easier than describing it

totes get that!

**Comment by ic4f** [comment]
I'll address #6 separately. 
I didn't factor out the checks for email and name (`if self.gdpr_clean:`) to keep that more explicit - so that it's immediately clear when those values are going to be redacted.
Didn't combine migrations - only the first one ended up being used.

**Review by hexylena — APPROVED** [review]

**Pull request merged**
