### PR TITLE
Change handling of static files

### PR DESCRIPTION
**Pull request by ic4f**
@hexylena how do you feel about this approach? 

1. `base.html` template assumes the existence of `galaxy.css` and
   `tiaas.css`. Both may or may not exist.
2. `galaxy.css` can be a symbolic link in `training/static/training/style/`
   pointing to the location of Galaxy's `base.css` (currently in
   `[galaxy root]/static/style/base.css`). It is not version controlled.
3. `tiass.css` is located in the same directory as `galaxy.css` and
   serves as the home to any custom styles that override the styles
   in `galaxy.css`.
4. Both files are copied to the root `static` directory by running
   the `collectstatic` app (see documentation for v. 3.1 here:
   https://docs.djangoproject.com/en/3.1/howto/static-files/ ).
   `collectstatic` should be run whenever any of these files is updated.

THOUGHTS/JUSTIFICATION:
It seems safer to have to occasionally run `collectstatic` to
update the linked Galaxy stylesheet versus to rely on it not to break
the app's layout.
Also, we are not guessing the location of `base.css`; local development is more streamlined, and it follows the approach suggested in the Django docs (which makes it easier for newcomers).

### CODE REVIEW

**Comment by ic4f** [comment]
The 2 subsequent commits (inline styles, tabs) are less important. I think they make things better,  but I can live without them.
The only real change I made, I think, [is here](https://github.com/usegalaxy-eu/tiaas2/pull/10/files#diff-70f03d9ba614dfe2431c4a9037e3de838c44d4b39c7e71db880cccab7edc239aL6): those styles will be now applied to `screen` (vs. `all`), which, as far as I can tell, doesn't make any difference here.

**Comment by hexylena** [comment]
I will never understand the rest of the world's dislike of tabs and insistence to rewrite them as spaces, but not a hill I'm going to die on, so, no worries.

> galaxy.css can be a symbolic link in training/static/training/style/ pointing to the location of Galaxy's base.css

So this is a little bit messy for deployment with ansible. https://github.com/usegalaxy-eu/ansible-tiaas2/blob/master/tasks/main.yml#L30 in the ansible role we do a force checkout which would wipe out that symlink every time. I'm a big fan of `force: true` in git modules to ensure no one is making changes on a server, that get lost. It's been an issue in the past so now I ensure the codebase is what it says it should be, always. I'm not sure how to work around this

> tiass.css

this is definitely an improvement.

> collectstatic should be run whenever any of these files is updated

handled in ansible, only "supported/official" way to deploy tiaas2, so, this task cannot be forgotten by admins. We already use collectstatic, btw, for all the js. https://github.com/usegalaxy-eu/ansible-tiaas2/blob/master/tasks/main.yml#L110

**Comment by ic4f** [comment]
> So this is a little bit messy for deployment with ansible. https://github.com/usegalaxy-eu/ansible-tiaas2/blob/master/tasks/main.yml#L30 in the ansible role we do a force checkout which would wipe out that symlink every time...

That link is part of `.gitignore`. Wouldn't that preserve it? (I did a local sanity check, and it works as expected, unless I'm missing something fundamental...)

Tabs vs spaces: same here, not my hill either. Thanks - and I would be happy with either option too. Reason for edit: very subjective; mostly for the sake of consistent display across editors. Multiple levels of nesting tend to make it more pronounced, which is always the case with html. Here, I was looking at adding some tag, and of course the indenting broke - one thing led to another, etc.

> handled in ansible, only "supported/official" way to deploy tiaas2

Of course! I missed that.

**Comment by ic4f** [comment]
..Also, creating that link could be added to the ansible role, with its value as a variable. Would that make sense?

**Comment by hexylena** [comment]
> Wouldn't that preserve it? (I did a local sanity check, and it works as expected, unless I'm missing something fundamental...)

Huh, maybe that's on me, I checked the docs, I thought that also removed non-checked-in files, but, I'm wrong. yay!

I guess that works even if it doesn't give me warm fuzzies, so, yeah, let's do that!

**Comment by ic4f** [comment]
> > Wouldn't that preserve it? (I did a local sanity check, and it works as expected, unless I'm missing something fundamental...)
> 
> Huh, maybe that's on me, I checked the docs, I thought that also removed non-checked-in files, but, I'm wrong. yay!

So I've reread the documentation of the ansible git module. It *does* imply that it will discard any changes **regardless** of whether or not the files in tracked are tracked. So I tested again, this time with ansible (previously I assumed that the ansible module's `force` parameter will mirror `git checkout --force`). It still behaves as expected: it discards any changes in the working directory *excluding untracked files*. In other words, it works after all: the link is preserved.

Merging.

**Comment by hexylena** [comment]
Will merge to master once we've updated ansible, but, cool, very exciting :)

**Pull request merged**
